#!/bin/bash

source /usr/local/lib/entrypoint.sh

set -e

root=$BIND_CONFIG/keys
config_keys=$BIND_CONFIG/named.conf.keys

if [[ -z $1 ]] ; then
	echo "usage: $0 <update key name>"
	echo "ex: $0 updater.test.com"
	exit 1
fi

mkdir --parents $root

log "Generating key: $1 ..."
export prefix=$(dnssec-keygen -a HMAC-MD5 -b 512 -K $root -n USER $1)

log "Adding key to $config_keys ..."
export name=$1.
export secret=$(cat $root/$prefix.key | awk '{print $7,$8}')
cp --backup=numbered $config_keys $config_keys.bak
envsubst "\$name \$secret" < /usr/local/share/bind/named.conf.keys.template >> $config_keys

log "Applying ownership and permissions ..."
chown root:bind $root/$prefix.*
chmod 0640 $root/$prefix*.key
chmod 0600 $root/$prefix*.private

