#!/bin/bash

source /usr/local/lib/entrypoint.sh

set -e -o pipefail

if [[ -z "${1}" ]] ; then
	echo "usage: ${0} <update key name>"
	echo "ex: ${0} updater.test.com"
	exit 1
fi

root="${BIND_CONFIG}/keys"
config_keys="${BIND_CONFIG}/named.conf.keys"
keyfile="${root}/K${1}.key"

install --directory --group=bind --mode=0750 --owner=bind "${root}"

log "Generating: ${keyfile} ..."
install --group=bind --mode=0440 --owner=bind /dev/null "${keyfile}"
tsig-keygen -a "${BIND_KEY_ALGORITHM}" "${1}" > "${keyfile}"

log "Adding key to ${config_keys} ..."
cp --backup=numbered "${config_keys}" "${config_keys}.bak"
cat "${keyfile}" >> "${config_keys}"

