#!/bin/bash

set -e

zone=test.com
ip=192.168.1.123
key=updater.$zone
revzone=1.168.192.in-addr.arpa

log "Starting supervisord ..."
/usr/bin/supervisord --configuration=/etc/supervisor/supervisord.conf &
sleep 1
while ! grep 'running$' /var/log/supervisor/bind-stderr*.log > /dev/null ; do
	log "Waiting for bind ..."
	sleep 1
done

log "Generating key: $key ..."
bind-keygen $key

log "Generating zone: $zone ..."
bind-zonegen $zone fwd $key

log "Generating zone: $revzone ..."
ZONE_EMAIL=admin.${zone}. ZONE_NAME_SERVER=ns1.${zone}. bind-zonegen $revzone 1918 $key

log "Reloading ..."
rndc reload

log "Testing nsupdate ..."
bind-test-nsupdate $zone $key $revzone $ip

log "--- Test Passed ---"
exit 0
